### ISSUE TITLE
Thrustmaster T16000M recognized as a game controller not a joystick

### ISSUE THREAD

**Issue by DanSo83-afk** [AntiMicroX/antimicrox#1042]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

![AntiMicroXT16000mControllerMapping](https://github.com/user-attachments/assets/450d9a65-f4ca-4e81-af4c-5c7276c52cfd)
The z-axis and several other buttons don't register any input, and a few buttons registered as a axis.

### Expected Behavior

For the joysticks to be recognized as T16000M's

### Environment

```markdown
Program Version 3.4.1
Compiled from packaging: GitHub Windows Release
Built Against SDL 2.30.6
Running With SDL 2.30.6
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

---------------------

#### Upvote & Fund

- If you find this issue important, mark it with 👍. It lets us see which fixes and features are demanded by the most users. 
- We're using [Polar.sh](https://polar.sh/AntiMicroX) so you can upvote and help fund this issue. It may incentivize some developers to contribute to this project and fix some bugs.
- Funded developer receives the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/AntiMicroX/antimicrox/issues/1042">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1042/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/AntiMicroX/antimicrox/issues/1042/pledge.svg">
</picture>
</a>

**Comment by pktiuk** [comment]
@DanSo83-afk     
This issue seems to be caused by underlying SDL library, which provides to AntiMicroX  information whether selected device supports Game controller interface or not. [SDL_IsGameController()](https://github.com/libsdl-org/SDL/blob/release-2.30.x/include/SDL_gamecontroller.h#L274)

I think this problem should be reported to them

There is also other issue linked with this device: https://github.com/AntiMicroX/antimicrox/issues/1039   
It may be linked
