### ISSUE TITLE
Mouse Support

### ISSUE THREAD

**Issue by 1NEGROUP** [AntiMicroX/antimicrox#137]
I Just Bought The Razer Naga Trinity and Downloaded This To Customize My Mouse However There is No Mouse Support.
I Think It Would Be Pretty Useful Especially For Those Who Buy Mice For Their Linux Desktops But The Software For Those Mice Is Only Available For Windows, This Would be a Nice Alternative
Also are You Guys on any Alt Networks Where There Would a Discussion For AntiMicroX?

**Comment by pktiuk** [comment]
I don't think AntiMicroX needs this functionality. It doesn't match other functionalities provided by this app. Moreover, dealing with mouses (especially these gaming ones) is quite a difficult task, because many of them have custom firmware and used custom protocols to deal with changing their settings.  
Adding it wouldn't provide any value for community, because there already tools for dealing with gaming mouses and keyboards.  
I think they are better tailored for this task.

I think you should check [Piper](https://github.com/libratbag/piper)  (it is quite universal) :video_game:    
You can also check https://openrazer.github.io/ if the first app wouldn't fit your needs

**Comment by pktiuk** [comment]
GitHub is our main mean of communication for now, and we don't plan to change it.  
Maybe we will later enable GitHub dicsussions here, but we will have to discuss it.
