### ISSUE TITLE
I've been trying to play valorant on remote using antimicro and every keybind seems to be working except cursor movement. All keyboard buttons will work along with the mouse buttons but I can't turn.

### ISSUE THREAD

**Issue by ttvCarrott** [AntiMicroX/antimicrox#167]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Configuration**
Version of antimicrox: 
Used package: 
System version:

**Additional context**

**Comment by vguttmann** [comment]
FYI, you need to fill in the fields in your first message, otherwise we can't help you that much here. Have you tried if a normal mouse works, and if reinstalling AntiMicroX or Valorant helps? Apparently, there have been mouse issues in recent valorant versions across platforms, so we need to rule out that its just valorant that's at fault here.

**Comment by vguttmann** [comment]
Also, as Valorant is a windows-exclusive game, and they have a rather strict anticheat, I don't think you are playing it on Linux. In this case, please be informed, that antimicro, which your title seems to indicate you are using, is no longer maintained, and that AntiMicroX aims to take the place of antimicro. However, at this point in time, there is not yet a working build of AntiMicroX for windows, and it may take some more time until we can address those issues.
