### ISSUE TITLE
GitHub Page links to old repository

### ISSUE THREAD

**Issue by Aurareus** [AntiMicroX/antimicrox#20]
_GitHub Page_, _Issues_ and _Wiki_ items in the _Help_ menu in the menu bar links to the old repository (https://github.com/juliagoda/antimicroX)

**Comment by pktiuk** [comment]
Thanks, I will take care of this (in terms of wiki, link pointing to an old repository is the good one, because we are not going to import this wiki yet).

**Comment by OlegPopow** [comment]
From what I have observed, the appropriate changes have already been introduced - https://github.com/AntiMicroX/antimicroX/commit/1022a289e778f177c8209d9ea255db8d860ddf99#diff-06b1446c4b9f9f1cf62986e0b1f7ca66

All that remains is to tag the new version, which is necessary in order not to mislead users. Although the changes made so far have been cosmetic, if someone compiles antimicroX from this repository and sees that the bugs should be reported in another one (and he can't do that anymore, because the old repository has been archived), the user may feel confused.

**Comment by OlegPopow** [comment]
I noticed that you can update README.md - the antimicrox-git package already has a new maintainer in AUR.

https://aur.archlinux.org/packages/antimicrox-git/

Maybe he should inform you about this fact? It would also be good to add information about the stable version of the package, because without this it is incomplete. 

Of course, it would also be worth adding the information that there is no need to compile on your own, because there is a pre-compiled package available in the chaotic-aur repository.

http://chaotic.bangl.de/chaotic-aur/x86_64/

I'm just an average person, but if I run some cool project on github, I would try to make reasearch to make it easier for users to use my project. After all, you have written so much about it...

**Comment by pktiuk** [comment]
I think this issue can be closed now.

**Comment by OlegPopow** [comment]
In my humble opinion you should close it only after you have tagged the new version. Most users use stable and 3.0.1 still links to the old repository (I mean the Help menu of course).
