### ISSUE TITLE
Turbo/Boost at 0.01ms

### ISSUE THREAD

**Issue by Louisw57** [AntiMicroX/antimicrox#280]
Hello, 
I have a suggestion and i would like this option on one of you'r next releases if it's possible. 
Change Turbo/Boost at 0.01 ms, actually is at 0.02 ms. 😊

**Comment by pktiuk** [comment]
Why should I change that?

**Comment by Louisw57** [comment]
Hello,
Me and my friend need this option for special mechacinal in fps games. 
With 0.02 ms i see a micro freeze. 
I try 0.01ms with 100tic/s with mouse settings (mwheel) , this settings corrige my problem, this is why i need 0.01ms turbo 😊

**Comment by pktiuk** [comment]
I found proper place in code and I could easily change this

```cpp
const int AdvanceButtonDialog::MINIMUMTURBO = 2;
```

But tbh I don't know why minimum turbo value is set to 2ms.

@Ryochan7 Do you  still remember the reason?   
Commit introducing this value: https://github.com/AntiMicro/antimicro/commit/79d919524157eccf5e6e46effa6e8bdeb649371c

**Comment by pktiuk** [comment]
Similar problem with turbo rate was mentioned once in https://github.com/AntiMicroX/antimicrox/issues/147

> What I'd like is the ability to set turbo input to as much as 100/s or 0.01 intervals which I believe would solve all jitteriness at the high end

**Comment by Ryochan7** [comment]
I cannot remember why I chose to express the turbo interval time in hundredths of a second and why the slider min is 2 (0.02 sec). Not sure if this was to keep the turbo range similar to what was used in Xpadder. A lower minimum could possibly have been doable but I doubt allowing even a 2 ms minimum would be doable in many apps. Having a key press time be reduced to 1 ms would likely cause many apps to miss the state change since multiple state changes would happen too quickly; it is one big reason Macros in DS4Windows don't work very well without added Wait times.

**Comment by Louisw57** [comment]
Hello @pktiuk ,

If it's not too complicated, I would be really grateful if this is applied on the Antimicrox 3.2.4 version :).

**Comment by pktiuk** [comment]
> but I doubt allowing even a 2 ms minimum would be doable in many apps. Having a key press time be reduced to 1 ms would likely cause many apps to miss the state change since multiple state changes would happen too quickly

This change could introduce some problems for other users and has a very small number of people who would actually ise it.
Closing.
