### ISSUE TITLE
Could not open uinput device file; need permissions for /dev/uinput

### ISSUE THREAD

**Issue by Ileca** [AntiMicroX/antimicrox#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is a really easy to fix issue for the user so I am just reporting this.
On Ubuntu 21.10, using the 3.2.1 deb, you are greeted with

> Could not open uinput device file
> Please check that you have permission to write to the device: /dev/uinput

when trying to start Antimicrox. Fixing the permission fixes the problem.
This looks related to https://github.com/AntiMicroX/antimicrox/wiki/Open-uinput-error while not the same issue.

On a side note, when using the current default antimicro package (why not antimicrox? I never used this package before because I thought antimicrox was a fork of antimicro >.>), when controlling the mouse, it appears to work but the cursor doesn't follow. I mean that the cursor doesn't move even though the action of moving the cursor works, like if it was an invisible one. Obviously, the latest version fixes that but I just want to give a heads-up that the current package is bugged. It's the 3.1.4-1 btw. Not sure how updating repos works so I didn't open a new issue as you might already be aware of that.

**Comment by mirabilos** [comment]
Paweł Kotiuk dixit:

***@***.*** Could you update this package any time soon?

Alright, putting it nearer the top on my TODO.

**Comment by Ileca** [comment]
You are right, the ACL are applied to /dev/uinput once you reboot your computer. You might want to add that to the readme.

**Comment by maxigaz** [comment]
I recently tried Sway 1.7 under Arch Linux, and I have the exact same problem with Antimicrox 3.2.5 (installed from the AUR): On launch, I'm greeted with the message, 'Could not open uinput device file; need permissions for /dev/uinput'

On the other hand, I don't have (and never have had) this issue with Antimicrox running under i3-gaps, so I'm not sure what the problem is.

I've also checked the wiki page [Open uinput error](https://github.com/AntiMicroX/antimicrox/wiki/Open-uinput-error), and I can confirm that `60-antimicrox-uinput.rules` is already installed (shipped with the AUR package).

**Comment by pktiuk** [comment]
Have you rebooted after installation?   
Maybe it could help.

**Comment by maxigaz** [comment]
> Have you rebooted after installation? Maybe it could help.

Yes, I have.

**Comment by pktiuk** [comment]
TBH I think something with your config is broken.   
To put it simply, AntiMicroX opened by you (as a regular user) cannot open file related to uinput.   
You can try to launch `sudo antimicrox` to check whether this fille can be accessed at all (maybe can't be opened not because of  permissions, but because this file does not exists or the path is wrong)

**Comment by maxigaz** [comment]
> You can try to launch `sudo antimicrox` to check whether this fille can be accessed at all (maybe can't be opened not because of permissions, but because this file does not exists or the path is wrong)

```
Authorization required, but no authorization protocol specified

[1]    2755 IOT instruction  sudo antimicrox
```

**Comment by pktiuk** [comment]
Then it is something related to your system. It is out of scope for AntiMicroX

**Comment by maxigaz** [comment]
After asking somewhere else, I found the solution: the kernel module uinput was not loaded, so I had to run `modprobe uinput` as root. Now, AntiMicroX works, even as a regular user.

(I'm leaving this here just in case anybody else runs into the same issue.)
