### ISSUE TITLE
Controllers in the wrong order

### ISSUE THREAD

**Issue by darksgan** [AntiMicroX/antimicrox#548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Controllers are detected in the wrong order, and it only happes with AntimicroX.. games, emulators (all of them), JoyToKey, even the "old" Antimicro, detect them in the right order.

Thanks and regards.

### Environment

```markdown
- OS: Windows 10
- AntiMicroX version: 3.2.5
```

### Anything else?

![image](https://user-images.githubusercontent.com/36720431/193950068-1bf1cc3b-3c3a-4f9e-9659-aa97df6f6678.png)

**Comment by pktiuk** [comment]
What do you mean "order" , order of connecting controllers, or numbers of slots in adapter like here:
![image](https://user-images.githubusercontent.com/45544416/193994760-00f388ea-25c2-4c91-92af-d0dc2fc30809.png)

**Comment by darksgan** [comment]
I mean, "How Windows" and other software see the controllers "numbered".

Look at the image attached, Windows recognize the Madcatz controllers as the first one, the old Antimicro too each time I start it (I pressed the Dpad Up to show it in the picture)... and all the emulators I use, and all the games, see my Madcatz controller as the 1st controller (Player 1 / Controller 1), but AntimicroX, always see it as the second controller (Controller 2).

If I unplug the "other controller" (with AntimicroX already closed), when I start AntimicroX again (with ONLY the Madcatz controller plugged) then the Madcatz is recognized by AntimicroX as the fisrt one (and as the only one plugged, of course). If I plug a second controller AFTER having AntimicroX started, the other controller is showed as the second one in AntimicroX

Then, if I closed AntimicroX, when I restart it, Madcatz is the second controller again, and the other one is showed as the "first controller" (Controller 1).

Is the only software that recognize the controllers in the wrong order, but... I'm sorry to say that I have no idea about why.

**Comment by pktiuk** [comment]
Could you tell me why it is an issue at all?   
Why this order matter? Is there any situation, when something is wrong because of this reversed order?

**Comment by pktiuk** [comment]
Closing due to lack of feedback

**Comment by Dschogo** [comment]
hey there, think im encountering the same problem.
There are two Problems with this, first is pretty minor but if the controllers got player number indicators, they can be messed up. But thats more or less just cosmetic.
The bigger problem is, that if the controllers get disconnected, the controller order gets "switched". I think antimicrox just labels the controller it sees first to 1 and so on. But when controllers are first connected and then antimicrox gets started or if all controllers connect at once (like xbox x360 with the dongle), the order gets messed up, since windows initially ordered them differently. 

Why is this an issue? Games, but most importantly emulators can switch players mid game (when a controller disconnects for various reasons). Having different controllers with random orders between restarting the pc/antimicrox can be a frustrating (speaking of different forms of gamepads like a wheel and traditional x360)

The windows controller sdl/api should return the "original" order which antimicrox should respect to create an uniform experience.

**Comment by pktiuk** [comment]
@Dschogo  
This seems to make sense.  
I can investigate it, but first, could you provide mi logs from two of these situations? (pads in correct order and pads in the wrong order)   

I can't guarantee anything, because AntiMicroX doesn't use Windows API, but SDL. If for SDL order of gamepads will also be wrong then I won't be able to do anything.

**Comment by Dschogo** [comment]
Okey after a bit of investigation, it seems to be kinda fixed by reinstalling all gamepad related drivers. Sometimes when restarting antimicrox while all Controllers are already connected, the gui labels controllers wrong, BUT the resulting output (testet xinput) is still the correct one.
So controller 1 (indicator 1 on controller) corresponds to player 1 in Xinput, gets labeled randomly in the gui, but still is "1" in games. 
I assume the gui just numbers them after first seen, but SDL actually rebinds them via the HID/Instance of the right controller - so the number in the gui isn't always a correct representation. Functionality wise everything works.

For me the "cosmetic number" isn't really important, so i'd close the issue.
