### ISSUE TITLE
Icons in tray menu only showing up as "X"

### ISSUE THREAD

**Issue by tawfeqfauzi** [AntiMicroX/antimicrox#56]
**Describe the bug**
Tray menu is supposed to (?) display icons on each option but they don't appear. This is probably more of an aesthetic problem, but I just wanted to report it. I think it'd be better to just remove the icons.

**Screenshots**
![IMG_4543](https://user-images.githubusercontent.com/68013133/94887828-e30a0180-04a9-11eb-9dac-bfc899849a77.jpg)

**Version**
3.1.1 deb

**Comment by pktiuk** [comment]
I have the same bug, but I forgot to report it :)

**Comment by pktiuk** [comment]
I will investigate it.

**Comment by pktiuk** [comment]
It appears that There are multiple problems with these icons.
Instead of using system-wide icons installer adds new icons to existing theme called `hicolor` and enforces usage of this theme, and something goes wrong while loading these icons, and then we get these :x:-es.
Moreover, there are some spare icons embedded in binaries (loaded in case if something goes wrong with previous ones), and they are badly linked.

Patch will be ready soon.
