### ISSUE TITLE
Assign buttons (or actions) to other gamepad keys

### ISSUE THREAD

**Issue by SixelAlexiS90** [AntiMicroX/antimicrox#65]
As the title say, it would really be great to have the ability to bind the controller buttons for actions instead of keyboard and mouse.

Eg: You double tap "RB" button and the program send the "L3" button input instead.
Something similar to what you can do with Steam Controller Configuration, but antimicro could work with any game out there (for example Windows 10 Store games, I've played Darksiders 3 with regular antimicro for windows with no issues).

I've read that it was one of the explored ideas for a future update but is anyone still working on that?

Thank you very much!!!

**Comment by pktiuk** [comment]
Currently, we are not working on adding new features, our main focus for now is to fix existing bugs, cleanup of repository and (maybe) restoring Windows support for AntiMicroX.

Do you mean something like this: https://github.com/AntiMicroX/antimicrox/issues/11 ?

**Comment by SixelAlexiS90** [comment]
> Currently, we are not working on adding new features, our main focus for now is to fix existing bugs, cleanup of repository and (maybe) restoring Windows support for AntiMicroX.
> 
> Do you mean something like this: #11 ?

Not really, I meant set gamepad buttons instead of keyboard/mouse. Basically add a gamepad tab so you can bind other gamepad buttons instead of keyboard or mouse.

As I said, just like Steam do:
https://steamcdn-a.akamaihd.net/steamcommunity/public/images/steamworks_docs/italian/legacy_bind.png

You can see that on "Y" button you can bind a keyboard/mouse button or another gamepad button too.
That's what I'm talking about basically.

**Comment by pktiuk** [comment]
I understand now.  
It is just mapping some gamepad buttons of (combinations of them) to other gamepad buttons. Thank to this we could use simpler pads (with smaller number of buttons) as alternative to gamepads with more buttons.

For now, I can say it would be feature not implemented in any foreseeable future, because it would firstly need to have implemented combinations of buttons and later we would have to think about using new library used for emulating gamepads and intercepting of some buttons may appear to be needed.

**Comment by OlegPopow** [comment]
> Currently, we are not working on adding new features, our main focus for now is to fix existing bugs, cleanup of repository and (maybe) restoring Windows support for AntiMicroX.

This "maybe" sounds extremely comical given the fact that not long ago you wrote

```
All I can tell, I fully agree that dropping Windows support by previous maintainer was a terrible decision, and we are going to restore it, this is one of our top priorities
```
and


```
I won't tell, that dropping support for 95% of potential users was a good decision.
```

So at the same time you think it was wrong and you are not going to do anything to fix it? I agree that fixing existing bugs is important (because this nasty, horrible, disgusting and disgusting previous developer did not solve it and left it on your shoulders) but it would be nice to listen to users and add some features. After all, it is you who are for the users, not the users for you.

**Comment by pktiuk** [comment]
Please avoid offtopic comments, it only makes issues and discussions less readable.

I won't answer your question, because you are clearly looking for confrontation and I don't have time for this.
This is the first warning.

**Comment by OlegPopow** [comment]
I am not looking for confrontation in any way. Please do not overinterpret my words. I just wanted to know a clear position on the release of the Windows version, because I admit it honestly - I got lost in it. First you write that it is very important to do it and soon afterwards that there will be a release 'maybe'. I think we deserve a clear statement whether we should wait or look for another program?

P.S. I take your warning (the first one) deadly seriously and I only wrote about it because you wrote about possible plans to release Windows yourself so I wanted to take this opportunity to make sure there is a point of waiting or looking for an alternative.

**Comment by pktiuk** [comment]
Ask questions regarding Windows version on windows issue.

**Comment by DWShuo** [comment]
is this currently not possible due to limitations of the SDL2 library?

**Comment by pktiuk** [comment]
> is this currently not possible due to limitations of the SDL2 library?

To be honest, I am not aware of any SDL2 limitations.

**Comment by pktiuk** [comment]
Dealing with this issue would probably require finding a way  for intercepting/hiding current gamepad, when our virtual gamepad is in use.  
as mentioned in https://github.com/AntiMicroX/antimicrox/discussions/463

**Comment by pktiuk** [comment]
## Mapping to gamepad buttons 

For now, I can say that mapping to another gamepad buttons is out of scope of antimicrox.

> AntiMicroX is a graphical program used to map gamepad keys to keyboard, mouse, scripts and macros.

Not for another gamepads or virtual devices (at least not for now).   
There are already some apps which let you map your gamepad to another one like x360ce

Moreover, I haven't found any proper (applicable in Windows and Linux without hacky solutions like [the ones in wiki](https://github.com/AntiMicroX/antimicrox/wiki/Methods-for-Disabling-Joystick-Reading-in-Linux)) way of intercepting/hiding gamepad actions.

## Button combinations

In terms of creating combinations of buttons, there is separate issue for this: https://github.com/AntiMicroX/antimicrox/issues/298 (so I will mark it as a duplicate)

**Comment by 0xjordyV** [comment]
Gello! do you have any plans on continuing this?
