### ISSUE TITLE
The uninstallation leaves several folders and files behind (cmake)

### ISSUE THREAD

**Issue by Hir-design** [AntiMicroX/antimicrox#68]
**Describe the bug**
As the title says, the uninstallation leaves several paths in the system. Below is a list:
```
/usr/include/antimicrox
/usr/share/antimicrox
/usr/share/antimicrox/images
/usr/share/antimicrox/translations
/usr/share/doc/antimicrox
/var/lib/systemd/coredump/core.antimicrox.1000.b432ffc9974547f19a3daace3c1deb63.11690.1603227781000000.zst
```

**To Reproduce**
simply uninstall the program after installing it

**Expected behavior**
All files and directories belonging to the program only, should be removed from the system

**Configuration**
Version of antimicrox: 3.1.2 (from last commit)
System version: Arch Linux

**Additional context**
I don't know if I'm thinking right, but the error may have something to do with the error reported [here](https://github.com/AntiMicroX/antimicrox/issues/57) (this is the last line)

**Comment by pktiuk** [comment]
I will check whether is it reproducible on debian-based systems.

**Comment by pktiuk** [comment]
@gombosg   
Odes it occur on Fedora-based systems?

**Comment by pktiuk** [comment]
@Hir-design   
How did you installed antimicrox?

**Comment by Hir-design** [comment]
This results from the building with cmake and make. If the program gives this option, I checked it, because I am a tester. I think that despite using packages, there shouldn't be such a situation. But you will do it as you think.

**Comment by OlegPopow** [comment]
Packages in Arch work properly (both classic and git) and remove the whole program - I checked. Nevertheless, I think that compiling with classic method (cmake, make, make install) should also uninstall 100% of installed files. This may cause unnecessary clutter. Maybe I'm blind but I don't remember this problem occurring earlier.

**Comment by gombosg** [comment]
> Does it occur on Fedora-based systems?

It can't since only files specified in the RPM specfile are copied to the system during install. Conversely, they are uninstalled, too. Only home folder stuff can remain.

**Comment by gombosg** [comment]
So yes, this is a (c)make issue in this case.

**Comment by pktiuk** [comment]
I have checked this for CMake and  there are only empty directories left behind.  No files are left behind.    
(Except the last one which is not installed by AntiMicroX, it is just a report file generated by the system, so it will be probably automatically deleted later).

I will check how deleting directories could be handled by CMake.

**Comment by pktiuk** [comment]
@AntiMicroX/members  
Have you tried to install AntiMicroX using cmake (`sudo cmake --install .`)?  
In my case it doesn't seem to work very well. In terms of integration with system it doesn't look good, system uses pixelated version of icon, tray icon doesn't load properly.

![obraz](https://user-images.githubusercontent.com/45544416/103024943-17450980-4551-11eb-884a-9573d2f3fe9a.png)
There are problems with uninstallation (cmake doesn't support uninstallation by default, and we there is created a special build target deleting files).  Moreover, to properly uninstall AntiMicroX we have to somewhere store `install_manifest.txt` and current uninstall target is just a complicated way of running 
```bash
xargs rm < install_manifest.txt
```


Maybe we should just mark installation via cmake as something not recommended?  
We could just add some additional instructions for packages and that should be enough for users willing to compile.  
For us-developers installing using cmake is not very useful, because we can just run compiled AntiMicroX from `build/bin` to test changes.

**Comment by zzpxyx** [comment]
I don't know too much about cmake, but personally I haven't used it for installing antimicro or AntiMicroX. I may be misunderstanding things here but essentially in order to properly uninstall stuff we'll have to know the manifest anyway, be it in a script we maintain or via package management systems.

**Comment by pktiuk** [comment]
Cmake doesn't use package management system, that's why it is such a messy solution.

**Comment by pktiuk** [comment]
Cmake is marked as not recommended way of installation due to problems with proper integration with system, messy uninstallation process (it is not controlled by any package manager, for uninstallation `install_manifest.txt` is needed, uninstallation leaves empty directories)
