### ISSUE TITLE
Doesn't save my configurations/Wont auto load

### ISSUE THREAD

**Issue by Devynko** [AntiMicroX/antimicrox#70]
Like the title says, It is not saving my configurations. 

I am clicking the save as, naming the config, then saving. When I open my files, its not there. 

**Configuration**
I am using elementary os, and I have downloaded the App Center version 3.1.2

**Comment by Devynko** [comment]
I fixed the issue by setting the profile directory to /home/devyn/.var/app/io.github.antimicrox.antimicrox

**Comment by Devynko** [comment]
I fixed the issue by setting the profile directory to /home/devyn/.var/app/io.github.antimicrox.antimicrox

**Comment by Gildum** [comment]
Thanks for the tip Devynko! I had the exact same issue on MX Linux 19.3 and your solution works!

By default the profiles were saved in the /home directory and the created files were hidden and have weird names:
.xdp_example1.SBDI10
.xdp_example2.XVLY00

Now that they are saved in .var/app/io.github.antimicrox.antimicrox/ the profiles are not hidden and properly named:
example3.gamecontroller.amgp

So since it does seem like a bug, wouldn't it be best to reopen this issue?

**Comment by pktiuk** [comment]
It is definitely a bug. I think  this is also caused by flatpak packaging. Just like https://github.com/AntiMicroX/antimicrox/issues/123.  
Maybe we should just change accessibility setting and grant antimicrox access to filesystem.

**Comment by pktiuk** [comment]
@gombosg What do you think? Could you take care of it?

**Comment by gombosg** [comment]
Yes, I'll take a look. :)

**Comment by gombosg** [comment]
@pktiuk I was able to repro this. This is only in Flatpak version.
When saving a config file
- If you give it no extension, or not `.amgp` extension, it would save like `.xdp-filename.gamecontroller.amgp-EAK6bq`
- If you give it `.amgp` extension manually, it saves the file correctly.

I need to figure out how this works, but IMO it's not a flatpak permission issue.

**Comment by gombosg** [comment]
We need to look at what [this](https://github.com/AntiMicroX/antimicrox/blob/8e35365c41c84ddc166a1ab7916af67b2fc6be14/src/joytabwidget.cpp#L793-L897) is doing since this is the save as window. It might not be able to properly access files for renaming, in a flatpak context.

**Comment by gombosg** [comment]
I narrowed down the problem area to [this](https://github.com/AntiMicroX/antimicrox/blob/8e35365c41c84ddc166a1ab7916af67b2fc6be14/src/joytabwidget.cpp#L833-L836).

Basically, it renames the file by adding an extension to it when the user hasn't set any.

What happens is that the flatpak doesn't have access to the host file system, but the [file chooser portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.FileChooser) makes _the selected file_ available:

> The selected files will be made accessible to the application via the document portal, and the returned URI will point into the document portal fuse filesystem in /run/user/$UID/doc/.

Looks like, we get a reference to the selected file as an URI, but when we rename it, we start pointing to a file that doesn't exist in the "portal fuse FS".

Let's play with `QFileDialog`...

**Comment by gombosg** [comment]
I tried manually setting the suffix, with no success.

Damn, found 2 related bugs, which point to many other:
https://github.com/flatpak/xdg-desktop-portal-gtk/issues/191
https://github.com/flatpak/xdg-desktop-portal/issues/496

Looks like this issue is not fixed.

I also tried setting a default file name, but it also didn't show up in the dialog.

The only workaround I currently see is setting `filesystem=home` access in the Flatpak manifest. Which is discouraged. 🤷🏽‍♂️

**Comment by pktiuk** [comment]
> The only workaround I currently see is setting filesystem=home access in the Flatpak manifest. Which is discouraged.

I think we should do it, at least until flatpak will fix this.  
But before doing it we should check safety of this change. Will changing filesystem affect currrent users and their saves? What will happen during update containing this change?

**Comment by gombosg** [comment]
There is no risk, so I'm releasing the new version.
