### ISSUE TITLE
Analog triggers can't be used for set selection (without workaround)

### ISSUE THREAD

**Issue by alphaniner** [AntiMicroX/antimicrox#702]
### Is there an existing issue for this?

- [X] I searched the existing issues and did not find anything similar.

### Current Behavior

For simple (on/off) buttons, right-clicking on the button's entry in the interface shows a **Set Select** sub-menu. But this sub-menu isn't present when right-clicking on an analog trigger.

### Expected Behavior

The **Set Select** sub-menu should be present on the context menu for analog triggers just like for simple buttons.

### Environment

```markdown
Program Version 3.3.2
Compiled from packaging: GitHub Portable Windows Release
Built Against SDL 2.0.20
Running With SDL 2.0.20
Using Qt 5.15.2
Using Event Handler: SendInput
Host OS: windows Version: 10 Architecture: x86_64
```

### Anything else?

In case it's relevant, my controller is Logitech F310. It has XInput and DirectInput modes, and the issue occurs in both modes.

Also, it is possible to use a work-around to set a trigger as a set selector, but it's unintuitive and a bit cumbersome. Mostly because it requires _temporarily_ making an assignment in order to get access to the Advanced menu.

**Comment by pktiuk** [comment]
The trigger button is more complex than others, depending on configuration, it may trigger one or two different events.          
In the current form user knows which event will be fired with a certain threshold, so adding this option to the context menu would be messy and a bit counterintuitive, moreover, this kind of problem should be not reported as a bug, because this is not a bug.
