### ISSUE TITLE
Upstream migration.

### ISSUE THREAD

**Issue by pktiuk** [AntiMicroX/antimicrox#85]
Recently we have been granted access to [legacy AntiMicro repository](https://github.com/antimicro/antimicro).

Our further steps are listed below:

**Comment by gombosg** [comment]
Maybe there was some misunderstanding, but my proposal is to touch `antimicro` as little as possible, treating it as legacy code, and not waste our time with backporting. IMO we just don't have the time and resources for that.

There is no 'upstream' `antimicro`, since it hasn't been in development for years. This `antimicrox` code _is_ the upstream now.

My proposal is to 
1. Leave a README notice in `antimicro` so that users know what is going on and how they can contribute.
2. If not present already, provide config migration & compatibility for `antimicro` users, first under Linux. You already did similar stuff when renaming the repo so this should be OK.
3. In the meantime, contact the [Debian maintainer](https://packages.debian.org/sid/antimicro) so that once we have a migration path, they could deprecate `antimicro` in favor of `antimicrox`.
4. Fix the Windows build in `antimicrox`
5. Then migrate Windows `antimicro` users to `antimicrox` by a README notice and possibly by archiving the `antimicro` repo once we reach feature parity.

What do you think about these steps? I can create issues for missing stuff.

**Comment by pktiuk** [comment]
I agree with everything, but I am not sure about migrating Windows users to AntiMicroX, because most of regular Windows users do not use sites as GitHub, bot other general purpose sites like SourceForge etc and they will never see its GitHub page.

**Comment by pktiuk** [comment]
We could just leave the entire development on AntiMicroX side, but it would be good to use traction this repository already has and push here something from time to time.

**Comment by gombosg** [comment]
> bot other general purpose download sites like SourceForge etc and they will never see its GitHub page

This is a logistics problem: identifying where users find `antimicro`. As I see the SF page: https://sourceforge.net/projects/antimicro.mirror/ is just a dumb mirror, and can simply be updated by adding a feature-compatible `antimicrox` release to the `antimicro` page.

We can also notify download sites like softpedia to update their releases once we have something useful released.

I'm just saying that our resources are limited, and if these problems can be answered by something else than doing more coding :slightly_smiling_face: then we should prefer that.

**Comment by pktiuk** [comment]
But there much more smaller, local sites like [this](https://www.dobreprogramy.pl/antimicro,Program,Windows,92108.html)  
And updating and finding all of them is nearly impossible.

We should wait with final decision until we will find out what exactly broke Windows and then decide.  
We have time, this repository was waiting 4 years, it can wait several additional months.  
Maybe we will find in the meantime some windows-savvy developers.

**Comment by gombosg** [comment]
I totally agree, what I'm saying is that these sites also only know about updates if
a) we notify them
b) they see a release a GH, and we can add an `antimicrox` release then.

I also hope that we can get some Windows help, too. :)

**Comment by pktiuk** [comment]
I have opened an issue for discussion about this topic:

https://github.com/AntiMicro/antimicro/issues/351

**Comment by gombosg** [comment]
Great! I opened issues here, see the checklist above.

**Comment by pktiuk** [comment]
> * Then migrate Windows `antimicro` users to `antimicrox` by a README notice and possibly by archiving the `antimicro` repo once we reach feature parity.

Before proceeding with the last point from this list I would like to discuss it: https://github.com/AntiMicro/antimicro/issues/351

**Comment by pktiuk** [comment]
I think Now, after archiving legacy repository, we can tell, that we finished this migration.
