### ISSUE TITLE
discord support server

### ISSUE THREAD

**Issue by AriaMoradi** [AntiMicroX/antimicrox#97]
How about creating a discord support server for antimicro(x)?

Anyone that has questions or problems could contact us and other users and we could help directly.

And when something is serious enough they will open an issue.

**Comment by gombosg** [comment]
It's doable, I have discord on my phone. The question is, how much extra value would this mean for users - and for us?

**Comment by AriaMoradi** [comment]
> It's doable, I have discord on my phone. The question is, how much extra value would this mean for users - and for us?

One of the apps I use [inorichi/tachiyomi](https://github.com/inorichi/tachiyomi) has one.
Surely it will take more time but we'll be getting more contribution from the community.

**Comment by pktiuk** [comment]
I am not sure about it. I think having discord server is good, but in our case it may not have too much added value.  
This app seems to be a bit too simple to need active support via discord.

Instead of this we should rather focus on our website: https://github.com/AntiMicroX/antimicrox.github.io and provide some basic instructions there (it would be a perfect non-programming issue).

**Comment by pktiuk** [comment]
I think it can be closed now. If you think differently please reopen.

**Comment by abdogm** [comment]
> I think it can be closed now. If you think differently please reopen.

well, this is actually a good idea
i know you already see it kind of useless because there won't be many people needing help with the software
but still, there is a small number of users who might need help directly with setting everything up like how to bind more than one key to a one button on the controller, how adjust the sensitivity of the analogs etc
there might be people who has issues with other stuff that no one ever encountered who knows
but the biggest benefit I can see of creating Discord server is for people to share their controller setup for their games, I know there is a repository for that but it does not include all games that people are looking for, and let's face it, majority are lazy to upload their controller profile to the Repository has a contribution, so sharing the files through discord seems much easier

after all it is just my opinion, tell me what you think ?
